### ISSUE TITLE
Dialog 2: Craving/HRS registration

### ISSUE THREAD

**Issue by KristellP** [PerfectFit-project/content-development#9]
Description: 
1. Help, I have a craving! 
2. Questions about the craving: how strong was it? where were you? what were you doing?
3. What the user has already tried to make the craving decrease

(Possibility to suggest a coping activity and to update the first-aid kit)

To do: 
- [x] Add relevant resources
- [x] Check dialog against base requirements

**Comment by Milonvv** [comment]
Remarks / questions
-	Is the dialog started by the user (and not by the VC)? For example, by letting the user type ‘help’?
-	A dialog / activity about creating a first aid kit will probably be preceding this HRS registration dialog. In this first aid kit dialog should be explained more about cravings, that it is normal to experience this, the consequences of cravings (How do (re)lapses occur?) and that the user can type ‘help’ when he / she experiences a strong craving.
-	Add to the questions: What do you feel / symptoms do you experience? What were you doing or what happened before your urge to smoke started?

Resources:
-	(Michie et al., 2011) description: BS6 Prompt self-recording: Help the smoker to establish a routine of recording potentially useful information (e.g. situations or times when urges are strong and less strong)
-	Experiment Nele: “There can be certain situations or routines in your daily life that often cause you to get cravings to smoke. For example, you might have experienced that if you go to bed very late and thus sleep less, you smoke more the next day.” 
-	Experiment Nele: “situations in which you might find it difficult to refrain from smoking. For example, this could be during your lunch break at work, when you meet your best friend, or when you watch TV. How could you deal with these situations so that you do NOT smoke? Write down your plans in a few words.”
-	Stopcoach: “Moeilijke momenten zijn de momenten dat je gewend was om te roken. Dat kan zijn: bij de koffie, in de pauze of na het eten. Wat zijn jouw moeilijke momenten?”


References
Michie, S., Hyder, N., Walia, A., & West, R. (2011). Development of a taxonomy of behaviour change techniques used in individual behavioural support for smoking cessation. Addictive Behaviors, 36(4), 315-319. https://doi.org/10.1016/j.addbeh.2010.11.016

**Comment by Milonvv** [comment]
We decided to separate this dialogue into two dialogues:
1.	Help I have a craving! (user asks VC for help) > dialog: VC helps user with coping with the HRS 
**2.	Reflection on the craving (at the end of the day, to reflect on the day and craving) > dialog: user and VC reflect on the craving and VC asks questions about craving** 

We will focus on dialog 2

**Comment by svenvanderburg** [comment]
Great work @nelealbers and @Milonvv! I really like it 👍 I read it out aloud and it seems like the general flow makes sense.

I left quite some suggestions for improvement in the document, some are written in specific points, but are applicable to the dialog in general.

Sorry, I didn't add any alternative utterances, but maybe that is also not a priority right now? (we can always add more alternative utterances if we have finished all dialogs)
